-- Seed initial 7 artworks from galeria.html
INSERT INTO artworks (id, name_es, name_en, description_es, description_en, long_description_es, long_description_en, inspiration_es, inspiration_en, size, technique_es, technique_en, materials_es, materials_en, image_key, tags, sort_order)
VALUES
  (
    'perla_inu',
    'Perla Inu',
    'Perla Inu',
    'Una reinterpretación humorística y moderna del famoso cuadro ''La joven con el arete de perla'' de Johannes Vermeer. Es una mezcla entre arte clásico y cultura pop digital.',
    'A humorous and modern reinterpretation of the famous painting ''Girl with a Pearl Earring'' by Johannes Vermeer. It''s a blend of classical art and digital pop culture.',
    '', '', '', '',
    '40 × 30 cm',
    'Óleo sobre lienzo',
    'Oil on canvas',
    '', '',
    'artworks/perla_inu/pintura.png',
    '["óleo", "contemporáneo"]',
    1
  ),
  (
    'el_retrato_de_una_culpa_silenciosa',
    'El retrato de una culpa silenciosa',
    'Portrait of a Silent Guilt',
    '1° Puesto - Ñamombe''u 2024. Obra inspirada en el libro ''Tarde de abril'' de Carlos Martini. ''Ciertos pasajes de nuestra vida no se borran nunca y allí adonde vamos están con nosotros''.',
    '1st Place - Ñamombe''u 2024. Work inspired by the book ''Tarde de abril'' by Carlos Martini. ''Certain passages of our life are never erased and wherever we go they are with us''.',
    '', '', '', '',
    '30 × 30 cm',
    'Óleo sobre lienzo',
    'Oil on canvas',
    '', '',
    'artworks/el_retrato_de_una_culpa_silenciosa/oleo.png',
    '["óleo", "monocromático"]',
    2
  ),
  (
    'la_tristeza_del_guason',
    'La tristeza del Guasón',
    'The Joker''s Sadness',
    'Este retrato muestra al personaje del Guasón (Joaquin Phoenix), con un enfoque emocional más íntimo. Se enfatiza su tristeza y vulnerabilidad.',
    'This portrait shows the Joker character (Joaquin Phoenix) with a more intimate emotional focus. It emphasizes his sadness and vulnerability.',
    '', '', '', '',
    '20 × 20 cm',
    'Gouache',
    'Gouache',
    '', '',
    'artworks/la_tristeza_del_guason/gouache.png',
    '["gouache", "tinta"]',
    3
  ),
  (
    'la_nina_y_el_gato_negro',
    'La niña y el gato negro',
    'The Girl and the Black Cat',
    'Ilustración de un cuento lleno de magia y una historia por descubrir. Una niña de mirada curiosa y estilo vintage junto a su misterioso gato en un fondo llenos de flores.',
    'Illustration of a tale full of magic and a story to discover. A girl with a curious look and vintage style alongside her mysterious cat on a background full of flowers.',
    '', '', '', '',
    '500 × 400 px',
    'Ilustración digital',
    'Digital illustration',
    '', '',
    'artworks/la_nina_y_el_gato_negro/ilustracion.png',
    '["ilustración", "digital"]',
    4
  ),
  (
    'pedro_pedro_pedro',
    'Pedro, Pedro, Pedro',
    'Pedro, Pedro, Pedro',
    'Historieta del Mapache Pedro. Ilustración digital del mapache que camina entre la vegetación del bosque, rodeado de hojas verdes y sombras naturales.',
    'Comic strip of Pedro the Raccoon. Digital illustration of the raccoon walking through forest vegetation, surrounded by green leaves and natural shadows.',
    '', '', '', '',
    '500 × 300 px',
    'Ilustración digital',
    'Digital illustration',
    '', '',
    'artworks/pedro_pedro_pedro/ilustracion.png',
    '["ilustración", "digital"]',
    5
  ),
  (
    'las_aventuras_de_capi_y_pajarito',
    'Las aventuras de Capi y Pajarito',
    'The Adventures of Capi and Pajarito',
    'Ilustración digital en pixelart para un juego educativo de programación. Los personajes principales, Capi y Pajarito en medio de la naturaleza de Paraguay.',
    'Pixel art digital illustration for an educational programming game. The main characters, Capi and Pajarito in the midst of Paraguay''s nature.',
    '', '', '', '',
    '500 × 400 px',
    'Pixelart',
    'Pixel art',
    '', '',
    'artworks/las_aventuras_de_capi_y_pajarito/pixelart.png',
    '["ilustración", "digital", "pixelart"]',
    6
  ),
  (
    'madre_e_hijo',
    'Madre e hijo',
    'Mother and Son',
    'Dibujo tradicional hecho a mano alazada inspirada en una fotografía real, donde las líneas de lápiz y grafito reinterpretan la calidez del momento compartido entre madre e hijo.',
    'Traditional freehand drawing inspired by a real photograph, where pencil and graphite lines reinterpret the warmth of the moment shared between mother and son.',
    '', '', '', '',
    '21 × 35 cm',
    'Dibujo tradicional',
    'Traditional drawing',
    '', '',
    'artworks/madre_e_hijo/dibujo.png',
    '["dibujo", "tradicional"]',
    7
  );
